### ISSUE TITLE
Byte field arithmetic fails with "TypeError: can't concat int to bytes"

### ISSUE THREAD

**Issue by randybuildsthings** [HBLink-org/hblink3#14]
Per https://dvswitch.groups.io/g/HBlink/message/2616

`Unhandled Error`
`Traceback (most recent call last):`
`  File "/usr/lib/python3/dist-packages/twisted/python/log.py", line 86, in callWithContext`
`    return context.call({ILogContext: newCtx}, func, *args, **kw)`
`  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext`
`    return self.currentContext().callWithContext(ctx, func, *args, **kw)`
`  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext`
`    return func(*args,**kw)`
`  File "/usr/lib/python3/dist-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite`
`    why = selectable.doRead()`
`--- <exception caught here> ---`
`  File "/usr/lib/python3/dist-packages/twisted/internet/udp.py", line 249, in doRead`
`    self.protocol.datagramReceived(data, addr)`
`  File "/opt/hblink3/hblink.py", line 603, in peer_datagramReceived`
`    self.dmrd_received(_peer_id, _rf_src, _dst_id, _seq, _slot, _call_type, _frame_type, _dtype_vseq, _stream_id, _data)`
`  File "./bridge_all.py", line 130, in dmrd_received`
`    if _seq > (self.STATUS[_slot]['RX_SEQ'] + 1):`
`builtins.TypeError: can't concat int to bytes`

There's a need for `int.from_bytes()` here, but we should look at the entirety of the code to make sure we're not just throwing duct tape on the problem.

**Comment by braymond1776** [comment]
I'm experiencing this same issue trying to set up and use a PEER
